version: "3.0"

services:
        laravel:
                build:
                        context: . 
                        dockerfile: Dockerfile-multistage-building.prd
                image: my-new-php-with-laravel-image-recently-builded
                container_name: laravel
                networks: 
                        - laranet
        nginx:
                build:
                        context: ../nginx/
                        dockerfile: Dockerfile.prd
                image: duduxs/nginx:prd
                container_name: nginx
                networks:
                        - laranet
                ports: 
                        - "8080:80"
                          
networks:
        laranet:
                driver: bridge
