version: '3'

services:
        database:
                container_name: mysql
                image: mysql:5.7
                command: --innodb-use-native-aio=0
                restart: always
                tty: true
                volumes: 
                        - ./mysql-volume:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=nodedb
                        - MYSQL_ROOT_PASSWORD=root
                networks:
                        - node-network
        app:
                container_name: node                
                build:
                      context: ../node/
                image: my-node-image-builded-by-docker-compose
                volumes:
                        - ../node/:/my-app
                networks:
                        - node-network
                ports:
                        - "3000:3000"
                tty: true


networks:
        node-network:
                driver: bridge        

