version: '3'

services:
        database:
                container_name: mysql
                image: mysql:5.7
                command: --innodb-use-native-aio=0
                restart: always
                tty: true
                volumes: 
                        - ./mysql-volume:/var/lib/mysql
                environment:
                        - MYSQL_DATABASE=nodedb
                        - MYSQL_ROOT_PASSWORD=root
                        - MYSQL_USER=root
                networks:
                        - node-network

networks:
        node-network:
                driver: bridge        

