version: "3.0"

services:
        laravel:
                image: duduxs/php-with-laravel:prd
                container_name: laravel
                networks: 
                        - laranet
        nginx:
                image: duduxs/nginx:prd
                container_name: nginx
                networks:
                        - laranet
                ports: 
                        - "8080:80"
                          
networks:
        laranet:
                driver: bridge
